version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nasa_pg
    environment:
      - POSTGRES_USER=nasa
      - POSTGRES_PASSWORD=nasa
      - POSTGRES_DB=nasa
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nasa"]
      interval: 5s
      timeout: 5s
      retries: 10

  neo4j:
    image: neo4j:5.23
    container_name: nasa_neo4j
    environment:
      - NEO4J_AUTH=neo4j/nasa
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "nasa", "RETURN 1;"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
  neo4j_data:
  neo4j_logs:



